// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqab6Z_-S1OVqw2AjCW5T-G6GSx1N1DF4',
    appId: '1:762356730465:web:b26e48bd40a94fabd33820',
    messagingSenderId: '762356730465',
    projectId: 'fir-app-7079c',
    authDomain: 'fir-app-7079c.firebaseapp.com',
    storageBucket: 'fir-app-7079c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirUIe2_6RaO9rxVEudXybbbpyb0CYMBo',
    appId: '1:762356730465:android:4791e3a59e47405ad33820',
    messagingSenderId: '762356730465',
    projectId: 'fir-app-7079c',
    storageBucket: 'fir-app-7079c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIQ5ZIUFcH6ViQfMNc1sxFgWMf6QpUu3U',
    appId: '1:762356730465:ios:af2eb598d934e3b5d33820',
    messagingSenderId: '762356730465',
    projectId: 'fir-app-7079c',
    storageBucket: 'fir-app-7079c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIQ5ZIUFcH6ViQfMNc1sxFgWMf6QpUu3U',
    appId: '1:762356730465:ios:af2eb598d934e3b5d33820',
    messagingSenderId: '762356730465',
    projectId: 'fir-app-7079c',
    storageBucket: 'fir-app-7079c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqab6Z_-S1OVqw2AjCW5T-G6GSx1N1DF4',
    appId: '1:762356730465:web:c47529f31ab86876d33820',
    messagingSenderId: '762356730465',
    projectId: 'fir-app-7079c',
    authDomain: 'fir-app-7079c.firebaseapp.com',
    storageBucket: 'fir-app-7079c.firebasestorage.app',
  );
}
